# Generated by Django 5.1.4 on 2026-06-16 06:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=512)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_shops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShopMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="accounts.role",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("tax_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("logo_url", models.URLField(blank=True)),
                ("receipt_footer", models.CharField(blank=True, max_length=512)),
                ("low_stock_default", models.PositiveIntegerField(default=5)),
                ("language", models.CharField(default="en", max_length=8)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "shop settings",
                "verbose_name_plural": "shop settings",
            },
        ),
        migrations.AddIndex(
            model_name="shop",
            index=models.Index(fields=["owner"], name="shops_shop_owner_i_de9788_idx"),
        ),
        migrations.AddIndex(
            model_name="shopmembership",
            index=models.Index(fields=["user"], name="shops_shopm_user_id_688347_idx"),
        ),
        migrations.AddIndex(
            model_name="shopmembership",
            index=models.Index(fields=["shop"], name="shops_shopm_shop_id_71b4fe_idx"),
        ),
        migrations.AddConstraint(
            model_name="shopmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "shop"), name="uniq_user_shop_membership"
            ),
        ),
    ]
