# Generated by Django 5.1.15 on 2026-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopsettings",
            name="currency",
            field=models.CharField(default="ETB", max_length=3),
        ),
        migrations.AlterField(
            model_name="shopsettings",
            name="timezone",
            field=models.CharField(default="Africa/Addis_Ababa", max_length=64),
        ),
    ]
