# Generated by Django 5.1.4 on 2026-06-23 06:04

import apps.common.money
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Signed: positive = stock in, negative = stock out."
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("adjustment", "Adjustment"),
                            ("damage", "Damage"),
                            ("expiry", "Expiry"),
                            ("return_in", "Return in"),
                            ("return_out", "Return out"),
                            ("reconcile", "Reconcile"),
                        ],
                        max_length=16,
                    ),
                ),
                ("unit_cost", apps.common.money.MoneyField(blank=True, null=True)),
                ("reference_type", models.CharField(blank=True, max_length=32)),
                ("reference_id", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to="catalog.product",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "product", "-created_at"],
                        name="inventory_i_shop_id_6bd67a_idx",
                    ),
                    models.Index(fields=["type"], name="inventory_i_type_e6388d_idx"),
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="inventory_i_referen_ace22e_idx",
                    ),
                ],
            },
        ),
    ]
