# Generated by Django 5.1.4 on 2026-07-04 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low stock"),
                            ("out_of_stock", "Out of stock"),
                            ("large_expense", "Large expense"),
                            ("large_void", "Large void"),
                            ("failed_login", "Failed logins"),
                            ("daily_summary", "Daily summary"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "Info"), ("warn", "Warning"), ("critical", "Critical")],
                        default="info",
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "-created_at"], name="notificatio_shop_id_9f16c5_idx"
                    ),
                    models.Index(fields=["shop", "read_at"], name="notificatio_shop_id_f6e47b_idx"),
                ],
            },
        ),
    ]
