/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /activity — audit trail for the active shop. Owners see everything;
         *     cashiers see only their own actions (plan §8). */
        get: operations["activity_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /activity — audit trail for the active shop. Owners see everything;
         *     cashiers see only their own actions (plan §8). */
        get: operations["activity_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/login — returns {access, refresh, user}. Records IP + activity. */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/logout — blacklist the supplied refresh token. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid. */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        get: operations["categories_list"];
        put?: never;
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        post: operations["categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        get: operations["categories_retrieve"];
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        put: operations["categories_update"];
        post?: never;
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        delete: operations["categories_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        patch: operations["categories_partial_update"];
        trace?: never;
    };
    "/api/v1/expense-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Owner-managed expense categories. */
        get: operations["expense_categories_list"];
        put?: never;
        /** @description Owner-managed expense categories. */
        post: operations["expense_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expense-categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Owner-managed expense categories. */
        get: operations["expense_categories_retrieve"];
        /** @description Owner-managed expense categories. */
        put: operations["expense_categories_update"];
        post?: never;
        /** @description Owner-managed expense categories. */
        delete: operations["expense_categories_destroy"];
        options?: never;
        head?: never;
        /** @description Owner-managed expense categories. */
        patch: operations["expense_categories_partial_update"];
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Shop expenses with optional receipt image. Owner only (plan §8). */
        get: operations["expenses_list"];
        put?: never;
        /** @description Shop expenses with optional receipt image. Owner only (plan §8). */
        post: operations["expenses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Shop expenses with optional receipt image. Owner only (plan §8). */
        get: operations["expenses_retrieve"];
        /** @description Shop expenses with optional receipt image. Owner only (plan §8). */
        put: operations["expenses_update"];
        post?: never;
        /** @description Shop expenses with optional receipt image. Owner only (plan §8). */
        delete: operations["expenses_destroy"];
        options?: never;
        head?: never;
        /** @description Shop expenses with optional receipt image. Owner only (plan §8). */
        patch: operations["expenses_partial_update"];
        trace?: never;
    };
    "/api/v1/inventory/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /inventory/adjust — manual signed stock movement → one ledger row
         *     + cached-stock update in a single DB transaction (plan §3.2). Owner only. */
        post: operations["inventory_adjust_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /inventory/transactions — the stock ledger for the active shop. Owner only. */
        get: operations["inventory_transactions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /inventory/transactions — the stock ledger for the active shop. Owner only. */
        get: operations["inventory_transactions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /me — profile + memberships + per-shop role. */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        get: operations["products_list"];
        put?: never;
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        post: operations["products_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        get: operations["products_retrieve"];
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        put: operations["products_update"];
        post?: never;
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        delete: operations["products_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        patch: operations["products_partial_update"];
        trace?: never;
    };
    "/api/v1/products/{id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Derived stock for a product: cached value and the live ledger sum. */
        get: operations["products_stock_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Export all products in the active shop as an .xlsx file. */
        get: operations["products_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Import/upsert products from an .xlsx file (keyed on SKU). Owner only. */
        post: operations["products_import_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Stock purchases. Owner only (cashiers are denied — plan §8). */
        get: operations["purchases_list"];
        put?: never;
        /** @description Stock purchases. Owner only (cashiers are denied — plan §8). */
        post: operations["purchases_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/purchases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Stock purchases. Owner only (cashiers are denied — plan §8). */
        get: operations["purchases_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description POS sales. Create is idempotent on client_uuid; void is owner-only. */
        get: operations["sales_list"];
        put?: never;
        /** @description POS sales. Create is idempotent on client_uuid; void is owner-only. */
        post: operations["sales_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description POS sales. Create is idempotent on client_uuid; void is owner-only. */
        get: operations["sales_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{id}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description POS sales. Create is idempotent on client_uuid; void is owner-only. */
        get: operations["sales_receipt_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POS sales. Create is idempotent on client_uuid; void is owner-only. */
        post: operations["sales_void_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/PATCH /settings — settings for the active shop. Owner only. */
        get: operations["settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description GET/PATCH /settings — settings for the active shop. Owner only. */
        patch: operations["settings_partial_update"];
        trace?: never;
    };
    "/api/v1/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /shops — the shops the current user can access (not shop-scoped). */
        get: operations["shops_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /shops — the shops the current user can access (not shop-scoped). */
        get: operations["shops_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        get: operations["suppliers_list"];
        put?: never;
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        post: operations["suppliers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        get: operations["suppliers_retrieve"];
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        put: operations["suppliers_update"];
        post?: never;
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        delete: operations["suppliers_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD viewset auto-scoped to the active shop, with RBAC.
         *
         *     Declare ``action_roles`` (e.g. {"create": ["owner"], ...}) to gate writes;
         *     reads stay open to any shop member by default. */
        patch: operations["suppliers_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityLog: {
            /** Format: uuid */
            readonly id: string;
            readonly action: string;
            readonly entity_type: string;
            readonly entity_id: string;
            readonly level: components["schemas"]["LevelEnum"];
            readonly metadata: unknown;
            readonly ip: string | null;
            /** Format: uuid */
            readonly user: string | null;
            /** Format: email */
            readonly user_email: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        Category: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        CategoryRequest: {
            name: string;
        };
        Expense: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            category?: string | null;
            readonly category_name: string;
            /** Format: int64 */
            amount: number;
            /** Format: date */
            date: string;
            description?: string;
            readonly receipt_image_url: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        ExpenseCategory: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        ExpenseCategoryRequest: {
            name: string;
        };
        ExpenseRequest: {
            /** Format: uuid */
            category?: string | null;
            /** Format: int64 */
            amount: number;
            /** Format: date */
            date: string;
            description?: string;
            /** Format: binary */
            receipt_image?: string | null;
        };
        InventoryTransaction: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly product: string;
            readonly product_name: string;
            readonly product_sku: string;
            /** @description Signed: positive = stock in, negative = stock out. */
            readonly quantity: number;
            readonly type: components["schemas"]["InventoryTransactionTypeEnum"];
            readonly unit_cost: number | null;
            readonly reference_type: string;
            readonly reference_id: string;
            /** Format: uuid */
            readonly user: string | null;
            /** Format: email */
            readonly user_email: string;
            readonly notes: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `purchase` - Purchase
         *     * `sale` - Sale
         *     * `adjustment` - Adjustment
         *     * `damage` - Damage
         *     * `expiry` - Expiry
         *     * `return_in` - Return in
         *     * `return_out` - Return out
         *     * `reconcile` - Reconcile
         * @enum {string}
         */
        InventoryTransactionTypeEnum: "purchase" | "sale" | "adjustment" | "damage" | "expiry" | "return_in" | "return_out" | "reconcile";
        /**
         * @description * `info` - Info
         *     * `warn` - Warning
         *     * `critical` - Critical
         * @enum {string}
         */
        LevelEnum: "info" | "warn" | "critical";
        LogoutRequest: {
            refresh: string;
        };
        Me: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly full_name: string;
            readonly is_active: boolean;
            readonly is_staff: boolean;
            readonly memberships: string;
        };
        /**
         * @description * `cash` - Cash
         *     * `bank` - Bank
         *     * `mobile_money` - Mobile money
         * @enum {string}
         */
        MethodEnum: "cash" | "bank" | "mobile_money";
        PaginatedActivityLogList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ActivityLog"][];
        };
        PaginatedCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Category"][];
        };
        PaginatedExpenseCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ExpenseCategory"][];
        };
        PaginatedExpenseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Expense"][];
        };
        PaginatedInventoryTransactionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["InventoryTransaction"][];
        };
        PaginatedProductList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Product"][];
        };
        PaginatedPurchaseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Purchase"][];
        };
        PaginatedSaleList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Sale"][];
        };
        PaginatedShopList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Shop"][];
        };
        PaginatedSupplierList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Supplier"][];
        };
        PatchedCategoryRequest: {
            name?: string;
        };
        PatchedExpenseCategoryRequest: {
            name?: string;
        };
        PatchedExpenseRequest: {
            /** Format: uuid */
            category?: string | null;
            /** Format: int64 */
            amount?: number;
            /** Format: date */
            date?: string;
            description?: string;
            /** Format: binary */
            receipt_image?: string | null;
        };
        PatchedProductRequest: {
            name?: string;
            sku?: string;
            barcode?: string;
            /** Format: uuid */
            category?: string | null;
            /** Format: uuid */
            supplier?: string | null;
            /** Format: int64 */
            purchase_price?: number;
            /** Format: int64 */
            selling_price?: number;
            unit?: string;
            /** Format: int64 */
            min_stock_alert?: number;
            status?: components["schemas"]["ProductStatusEnum"];
        };
        PatchedShopSettingsRequest: {
            currency?: string;
            /** Format: decimal */
            tax_rate?: string;
            /** Format: uri */
            logo_url?: string;
            receipt_footer?: string;
            /** Format: int64 */
            low_stock_default?: number;
            language?: string;
            timezone?: string;
        };
        PatchedSupplierRequest: {
            name?: string;
            phone?: string;
            address?: string;
            notes?: string;
        };
        Payment: {
            /** Format: uuid */
            readonly id: string;
            readonly method: components["schemas"]["MethodEnum"];
            readonly amount: number;
            /** Format: date-time */
            readonly received_at: string;
        };
        PaymentInputRequest: {
            method: components["schemas"]["MethodEnum"];
            amount: number;
        };
        /**
         * @description * `paid` - Paid
         *     * `partial` - Partial
         *     * `unpaid` - Unpaid
         * @enum {string}
         */
        PaymentStatusEnum: "paid" | "partial" | "unpaid";
        Product: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            sku: string;
            barcode?: string;
            /** Format: uuid */
            category?: string | null;
            readonly category_name: string;
            /** Format: uuid */
            supplier?: string | null;
            readonly supplier_name: string;
            /** Format: int64 */
            purchase_price?: number;
            /** Format: int64 */
            selling_price?: number;
            unit?: string;
            /** Format: int64 */
            min_stock_alert?: number;
            status?: components["schemas"]["ProductStatusEnum"];
            readonly stock_cached: number;
            readonly is_low_stock: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ProductRequest: {
            name: string;
            sku: string;
            barcode?: string;
            /** Format: uuid */
            category?: string | null;
            /** Format: uuid */
            supplier?: string | null;
            /** Format: int64 */
            purchase_price?: number;
            /** Format: int64 */
            selling_price?: number;
            unit?: string;
            /** Format: int64 */
            min_stock_alert?: number;
            status?: components["schemas"]["ProductStatusEnum"];
        };
        /**
         * @description * `active` - Active
         *     * `inactive` - Inactive
         * @enum {string}
         */
        ProductStatusEnum: "active" | "inactive";
        Purchase: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly supplier: string | null;
            readonly supplier_name: string;
            readonly total: number;
            readonly amount_paid: number;
            readonly payment_status: components["schemas"]["PaymentStatusEnum"];
            /** Format: date */
            readonly date: string;
            readonly notes: string;
            readonly items: components["schemas"]["PurchaseItem"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        PurchaseCreateRequest: {
            /** Format: uuid */
            supplier?: string | null;
            items: components["schemas"]["PurchaseItemInputRequest"][];
            /** @default 0 */
            amount_paid: number;
            /** Format: date */
            date?: string | null;
            /** @default  */
            notes: string;
        };
        PurchaseItem: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly product: string;
            readonly product_name: string;
            readonly product_sku: string;
            readonly quantity: number;
            readonly unit_cost: number;
            readonly line_total: number;
        };
        PurchaseItemInputRequest: {
            /** Format: uuid */
            product: string;
            quantity: number;
            unit_cost: number;
        };
        /** @description Flattened, display-ready payload for printing (plan §11 Phase 2). */
        Receipt: {
            /** Format: uuid */
            readonly id: string;
            readonly shop_name: string;
            readonly shop_address: string;
            readonly cashier_name: string;
            readonly currency: string;
            readonly receipt_footer: string;
            readonly subtotal: number;
            readonly discount: number;
            readonly tax: number;
            readonly total: number;
            readonly status: components["schemas"]["Status676Enum"];
            readonly amount_paid: number;
            readonly change: number;
            readonly items: components["schemas"]["SaleItem"][];
            readonly payments: components["schemas"]["Payment"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        Sale: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly client_uuid: string;
            /** Format: uuid */
            readonly cashier: string;
            /** Format: email */
            readonly cashier_email: string;
            readonly subtotal: number;
            readonly discount: number;
            readonly tax: number;
            readonly total: number;
            readonly status: components["schemas"]["Status676Enum"];
            readonly notes: string;
            readonly amount_paid: number;
            readonly change: number;
            readonly items: components["schemas"]["SaleItem"][];
            readonly payments: components["schemas"]["Payment"][];
            /** Format: date-time */
            readonly voided_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        SaleCreateRequest: {
            /** Format: uuid */
            client_uuid: string;
            items: components["schemas"]["SaleItemInputRequest"][];
            payments: components["schemas"]["PaymentInputRequest"][];
            /** @default 0 */
            discount: number;
            /** @default 0 */
            tax: number;
            /** @default  */
            notes: string;
        };
        SaleItem: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly product: string;
            readonly name_snapshot: string;
            readonly sku_snapshot: string;
            readonly unit_price_snapshot: number;
            readonly quantity: number;
            readonly line_total: number;
        };
        SaleItemInputRequest: {
            /** Format: uuid */
            product: string;
            quantity: number;
            unit_price?: number;
        };
        Shop: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly address: string;
            readonly phone: string;
            readonly my_role: string | null;
            readonly currency: string;
            readonly tax_rate: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        ShopSettings: {
            currency?: string;
            /** Format: decimal */
            tax_rate?: string;
            /** Format: uri */
            logo_url?: string;
            receipt_footer?: string;
            /** Format: int64 */
            low_stock_default?: number;
            language?: string;
            timezone?: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `completed` - Completed
         *     * `voided` - Voided
         * @enum {string}
         */
        Status676Enum: "completed" | "voided";
        /** @description Input for POST /inventory/adjust — a manual, signed stock movement. */
        StockAdjustmentRequest: {
            /** Format: uuid */
            product: string;
            quantity: number;
            type: components["schemas"]["StockAdjustmentTypeEnum"];
            /** @default  */
            notes: string;
        };
        /**
         * @description * `adjustment` - adjustment
         *     * `damage` - damage
         *     * `expiry` - expiry
         *     * `return_in` - return_in
         *     * `return_out` - return_out
         * @enum {string}
         */
        StockAdjustmentTypeEnum: "adjustment" | "damage" | "expiry" | "return_in" | "return_out";
        Supplier: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            phone?: string;
            address?: string;
            notes?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        SupplierRequest: {
            name: string;
            phone?: string;
            address?: string;
            notes?: string;
        };
        /** @description JWT login. Adds profile claims and a `user` block to the response. */
        TokenPairRequest: {
            email: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    activity_list: {
        parameters: {
            query?: {
                action?: string;
                /** @description * `info` - Info
                 *     * `warn` - Warning
                 *     * `critical` - Critical */
                level?: "critical" | "info" | "warn";
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedActivityLogList"];
                };
            };
        };
    };
    activity_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this activity log. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLog"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenPairRequest"];
                "multipart/form-data": components["schemas"]["TokenPairRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description No response body */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategoryList"];
                };
            };
        };
    };
    categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoryRequest"];
                "multipart/form-data": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoryRequest"];
                "multipart/form-data": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategoryRequest"];
                "multipart/form-data": components["schemas"]["PatchedCategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    expense_categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExpenseCategoryList"];
                };
            };
        };
    };
    expense_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ExpenseCategoryRequest"];
                "multipart/form-data": components["schemas"]["ExpenseCategoryRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseCategory"];
                };
            };
        };
    };
    expense_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this expense category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseCategory"];
                };
            };
        };
    };
    expense_categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this expense category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ExpenseCategoryRequest"];
                "multipart/form-data": components["schemas"]["ExpenseCategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseCategory"];
                };
            };
        };
    };
    expense_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this expense category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    expense_categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this expense category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedExpenseCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedExpenseCategoryRequest"];
                "multipart/form-data": components["schemas"]["PatchedExpenseCategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseCategory"];
                };
            };
        };
    };
    expenses_list: {
        parameters: {
            query?: {
                category?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExpenseList"];
                };
            };
        };
    };
    expenses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ExpenseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ExpenseRequest"];
                "application/json": components["schemas"]["ExpenseRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
    expenses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this expense. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
    expenses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this expense. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ExpenseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ExpenseRequest"];
                "application/json": components["schemas"]["ExpenseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
    expenses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this expense. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    expenses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this expense. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedExpenseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedExpenseRequest"];
                "application/json": components["schemas"]["PatchedExpenseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
    inventory_adjust_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockAdjustmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StockAdjustmentRequest"];
                "multipart/form-data": components["schemas"]["StockAdjustmentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryTransaction"];
                };
            };
        };
    };
    inventory_transactions_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                product?: string;
                /** @description A search term. */
                search?: string;
                /** @description * `purchase` - Purchase
                 *     * `sale` - Sale
                 *     * `adjustment` - Adjustment
                 *     * `damage` - Damage
                 *     * `expiry` - Expiry
                 *     * `return_in` - Return in
                 *     * `return_out` - Return out
                 *     * `reconcile` - Reconcile */
                type?: "adjustment" | "damage" | "expiry" | "purchase" | "reconcile" | "return_in" | "return_out" | "sale";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInventoryTransactionList"];
                };
            };
        };
    };
    inventory_transactions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this inventory transaction. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryTransaction"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    products_list: {
        parameters: {
            query?: {
                category?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /** @description * `active` - Active
                 *     * `inactive` - Inactive */
                status?: "active" | "inactive";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductList"];
                };
            };
        };
    };
    products_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductRequest"];
                "multipart/form-data": components["schemas"]["ProductRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductRequest"];
                "multipart/form-data": components["schemas"]["ProductRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    products_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProductRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProductRequest"];
                "multipart/form-data": components["schemas"]["PatchedProductRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_stock_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    products_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    products_import_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    purchases_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description * `paid` - Paid
                 *     * `partial` - Partial
                 *     * `unpaid` - Unpaid */
                payment_status?: "paid" | "partial" | "unpaid";
                /** @description A search term. */
                search?: string;
                supplier?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPurchaseList"];
                };
            };
        };
    };
    purchases_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PurchaseCreateRequest"];
                "multipart/form-data": components["schemas"]["PurchaseCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Purchase"];
                };
            };
        };
    };
    purchases_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this purchase. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Purchase"];
                };
            };
        };
    };
    sales_list: {
        parameters: {
            query?: {
                cashier?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /** @description * `completed` - Completed
                 *     * `voided` - Voided */
                status?: "completed" | "voided";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSaleList"];
                };
            };
        };
    };
    sales_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SaleCreateRequest"];
                "multipart/form-data": components["schemas"]["SaleCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sale"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sale"];
                };
            };
        };
    };
    sales_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this sale. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sale"];
                };
            };
        };
    };
    sales_receipt_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this sale. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
        };
    };
    sales_void_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this sale. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sale"];
                };
            };
        };
    };
    settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopSettings"];
                };
            };
        };
    };
    settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedShopSettingsRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedShopSettingsRequest"];
                "multipart/form-data": components["schemas"]["PatchedShopSettingsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopSettings"];
                };
            };
        };
    };
    shops_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedShopList"];
                };
            };
        };
    };
    shops_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this shop. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shop"];
                };
            };
        };
    };
    suppliers_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSupplierList"];
                };
            };
        };
    };
    suppliers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SupplierRequest"];
                "multipart/form-data": components["schemas"]["SupplierRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
        };
    };
    suppliers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this supplier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
        };
    };
    suppliers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this supplier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SupplierRequest"];
                "multipart/form-data": components["schemas"]["SupplierRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
        };
    };
    suppliers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this supplier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suppliers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this supplier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSupplierRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSupplierRequest"];
                "multipart/form-data": components["schemas"]["PatchedSupplierRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
        };
    };
}
