# Generated by Django 5.1.4 on 2026-06-24 12:08

import apps.common.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="payable_cached",
            field=apps.common.money.MoneyField(default=0),
        ),
    ]
